<html>
    <head>
    <link rel="stylesheet" href="css/style.css">
    </head>
    <body>
	<div class="table" align="center">
		<table border="1" width="350px" align="center">
			<tr align="center">
				<td colspan="7"><b>ΑΓΟΝΕΣ ΠΟΔΟΣΦΑΙΡΟΥ</b></td>
			</tr>
			<tr>
				<td colspan="7">&nbsp;</td>
			</tr>
			<tr>
				<td><b>&nbsp;</b></td>
				<td><b>Ομάδα</b></td>
				<td><b>Βαθμοί</b></td>
				<td><b>Αγώνες</b></td>
				<td><b>Νίκες</b></td>
				<td><b>Ισοπαλίες</b></td>
				<td><b>Ήττες</b></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
			</tr>
            <tr>
                <td></td>
                <td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
            </tr>
		</table>
	</div>
    </body>
</html>
